In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers

2026-03-21 15:49:59.171860: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1774108199.414128      17 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1774108199.483024      17 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1774108200.026920      17 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1774108200.026972      17 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1774108200.026975      17 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1774108200.026978      17 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

In [2]:
df = pd.read_csv('/kaggle/input/datasets/vivekyash/heart-failure-prediction-deep-learning-ann/heart_failure_clinical_records_dataset.csv')
df

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,62.0,0,61,1,38,1,155000.00,1.1,143,1,1,270,0
295,55.0,0,1820,0,38,0,270000.00,1.2,139,0,0,271,0
296,45.0,0,2060,1,60,0,742000.00,0.8,138,0,0,278,0
297,45.0,0,2413,0,38,0,140000.00,1.4,140,1,1,280,0
298,50.0,0,196,0,45,0,395000.00,1.6,136,1,1,285,0

In [3]:
df.columns

Index(['age', 'anaemia', 'creatinine_phosphokinase', 'diabetes',
       'ejection_fraction', 'high_blood_pressure', 'platelets',
       'serum_creatinine', 'serum_sodium', 'sex', 'smoking', 'time',
       'DEATH_EVENT'],
      dtype='object')

In [4]:
x = df[['age', 'anaemia', 'creatinine_phosphokinase', 'diabetes',
       'ejection_fraction', 'high_blood_pressure', 'platelets',
       'serum_creatinine', 'serum_sodium', 'sex', 'smoking', 'time']]
y = df[['DEATH_EVENT']]

In [5]:
from sklearn.preprocessing import MinMaxScaler

In [6]:
x_min = x.min()
x_max = x.max()
x_scaled = (x - x_min)/(x_max - x_min + 1e-8)
x_scaled

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time
0,0.636364,0.0,0.071319,0.0,0.090909,1.0,0.290823,0.157303,0.485714,1.0,0.0,0.000000
1,0.272727,0.0,1.000000,0.0,0.363636,0.0,0.288833,0.067416,0.657143,1.0,0.0,0.007117
2,0.454545,0.0,0.015693,0.0,0.090909,0.0,0.165960,0.089888,0.457143,1.0,1.0,0.010676
3,0.181818,1.0,0.011227,0.0,0.090909,0.0,0.224148,0.157303,0.685714,1.0,0.0,0.010676
4,0.454545,1.0,0.017479,1.0,0.090909,0.0,0.365984,0.247191,0.085714,0.0,0.0,0.014235
...,...,...,...,...,...,...,...,...,...,...,...,...
294,0.400000,0.0,0.004848,1.0,0.363636,1.0,0.157474,0.067416,0.857143,1.0,1.0,0.946619
295,0.272727,0.0,0.229268,0.0,0.363636,0.0,0.296884,0.078652,0.742857,0.0,0.0,0.950178
296,0.090909,0.0,0.259888,1.0,0.696970,0.0,0.869075,0.033708,0.714286,0.0,0.0,0.975089
297,0.090909,0.0,0.304925,0.0,0.363636,0.0,0.139290,0.101124,0.771429,1.0,1.0,0.982206
298,0.181818,0.0,0.022072,0.0,0.469697,0.0,0.448418,0.123596,0.657143,1.0,1.0,1.000000

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y, test_size = 0.25, random_state = 42 )

In [8]:
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'

In [9]:
model = keras.Sequential([
    layers.Input(shape=(x_train.shape[1],)),
    layers.Dense(8, activation= 'relu'),
    layers.Dense(6, activation= 'relu'),
    layers.Dense(4, activation= 'relu'),
    layers.Dense(2, activation= 'relu'),
    layers.Dense(1, activation= 'linear')
])

2026-03-21 15:50:27.658820: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

In [10]:
model.compile(optimizer='sgd', loss='BinaryCrossentropy', metrics = ['accuracy'])

In [11]:
history = model.fit(
    x_train.values, y_train.values, validation_data=(x_test.values,y_test.values),
    epochs = 100,batch_size = 4,verbose = 1
)

Epoch 1/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.6923 - loss: 4.8582 - val_accuracy: 0.5867 - val_loss: 0.8070
Epoch 2/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6761 - loss: 0.6608 - val_accuracy: 0.5867 - val_loss: 0.7417
Epoch 3/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7273 - loss: 0.5910 - val_accuracy: 0.5867 - val_loss: 0.7142
Epoch 4/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7505 - loss: 0.5611 - val_accuracy: 0.5867 - val_loss: 0.6886
Epoch 5/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7094 - loss: 0.6053 - val_accuracy: 0.5867 - val_loss: 0.7009
Epoch 6/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7487 - loss: 0.5788 - val_accuracy: 0.5867 - val_loss: 0.7087
Epoch 7/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6883 - loss: 0.6266 - val_accuracy: 0.5867 - val_loss: 0.7115
Epoch 8/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6633 - loss: 0.6442 - val_accuracy: 0.5867 - val_loss: 0.7371
Epoch 9/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7019 - loss: 0.6119 - val_accuracy: 0.5867 - val_loss: 0.7151
Epoch 10/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7395 - loss: 0.5823 - val_accuracy: 0.5867 - val_loss: 0.7022
Epoch 11/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7192 - loss: 0.5967 - val_accuracy: 0.5867 - val_loss: 0.7030
Epoch 12/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7687 - loss: 0.5531 - val_accuracy: 0.5867 - val_loss: 0.6902
Epoch 13/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7369 - loss: 0.5859 - val_accuracy: 0.5867 - val_loss: 0.7188
Epoch 14/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6726 - loss: 0.6383 - val_accuracy: 0.5867 - val_loss: 0.7307
Epoch 15/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7640 - loss: 0.5492 - val_accuracy: 0.5867 - val_loss: 0.7000
Epoch 16/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7221 - loss: 0.5979 - val_accuracy: 0.5867 - val_loss: 0.7159
Epoch 17/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6944 - loss: 0.6187 - val_accuracy: 0.5867 - val_loss: 0.7279
Epoch 18/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6983 - loss: 0.6184 - val_accuracy: 0.5867 - val_loss: 0.7171
Epoch 19/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7151 - loss: 0.5997 - val_accuracy: 0.5867 - val_loss: 0.7112
Epoch 20/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7023 - loss: 0.6072 - val_accuracy: 0.5867 - val_loss: 0.7274
Epoch 21/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7179 - loss: 0.5957 - val_accuracy: 0.5867 - val_loss: 0.7170
Epoch 22/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6940 - loss: 0.6219 - val_accuracy: 0.5867 - val_loss: 0.7362
Epoch 23/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7072 - loss: 0.6115 - val_accuracy: 0.5867 - val_loss: 0.7081
Epoch 24/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7153 - loss: 0.6012 - val_accuracy: 0.5867 - val_loss: 0.7049
Epoch 25/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7407 - loss: 0.5868 - val_accuracy: 0.5867 - val_loss: 0.7072
Epoch 26/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7116 - loss: 0.5966 - val_accuracy: 0.5867 - val_loss: 0.7046
Epoch 27/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7627 - loss: 0.5541 - val_accuracy: 0.5867 - val_loss: 0.6951
Epoch 28/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6898 - loss: 0.6139 - val_accuracy: 0.5867 - val_loss: 0.7302
Epoch 29/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7396 - loss: 0.5728 - val_accuracy: 0.5867 - val_loss: 0.6949
Epoch 30/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6626 - loss: 0.6309 - val_accuracy: 0.5867 - val_loss: 0.7151
Epoch 31/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7016 - loss: 0.6084 - val_accuracy: 0.5867 - val_loss: 0.7416
Epoch 32/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6900 - loss: 0.6272 - val_accuracy: 0.5867 - val_loss: 0.7374
Epoch 33/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6843 - loss: 0.6271 - val_accuracy: 0.5867 - val_loss: 0.7210
Epoch 34/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7768 - loss: 0.5390 - val_accuracy: 0.5867 - val_loss: 0.7010
Epoch 35/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7430 - loss: 0.5735 - val_accuracy: 0.5867 - val_loss: 0.7045
Epoch 36/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6682 - loss: 0.6334 - val_accuracy: 0.5867 - val_loss: 0.7145
Epoch 37/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7127 - loss: 0.5900 - val_accuracy: 0.5867 - val_loss: 0.7415
Epoch 38/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6681 - loss: 0.6259 - val_accuracy: 0.5867 - val_loss: 0.7572
Epoch 39/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7046 - loss: 0.6003 - val_accuracy: 0.5867 - val_loss: 0.7393
Epoch 40/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7090 - loss: 0.6061 - val_accuracy: 0.5867 - val_loss: 0.7283
Epoch 41/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7510 - loss: 0.5560 - val_accuracy: 0.5867 - val_loss: 0.7035
Epoch 42/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7504 - loss: 0.5816 - val_accuracy: 0.5867 - val_loss: 0.7226
Epoch 43/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7120 - loss: 0.5975 - val_accuracy: 0.5867 - val_loss: 0.7563
Epoch 44/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6834 - loss: 0.6198 - val_accuracy: 0.5867 - val_loss: 0.7530
Epoch 45/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6791 - loss: 0.6217 - val_accuracy: 0.5867 - val_loss: 0.7343
Epoch 46/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7121 - loss: 0.5849 - val_accuracy: 0.5867 - val_loss: 0.7239
Epoch 47/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7211 - loss: 0.5686 - val_accuracy: 0.5867 - val_loss: 0.7270
Epoch 48/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6850 - loss: 0.6029 - val_accuracy: 0.6000 - val_loss: 0.7087
Epoch 49/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7225 - loss: 0.5690 - val_accuracy: 0.5867 - val_loss: 0.7320
Epoch 50/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6992 - loss: 0.5846 - val_accuracy: 0.6000 - val_loss: 0.7219
Epoch 51/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6956 - loss: 0.5932 - val_accuracy: 0.5867 - val_loss: 0.7476
Epoch 52/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6934 - loss: 0.5951 - val_accuracy: 0.5867 - val_loss: 0.7767
Epoch 53/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7227 - loss: 0.5469 - val_accuracy: 0.6000 - val_loss: 0.7117
Epoch 54/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7429 - loss: 0.5403 - val_accuracy: 0.5867 - val_loss: 0.7075
Epoch 55/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7424 - loss: 0.5337 - val_accuracy: 0.5733 - val_loss: 0.7114
Epoch 56/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7347 - loss: 0.5229 - val_accuracy: 0.5733 - val_loss: 0.6872
Epoch 57/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7677 - loss: 0.5194 - val_accuracy: 0.5733 - val_loss: 0.6992
Epoch 58/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7233 - loss: 0.5708 - val_accuracy: 0.5733 - val_loss: 0.6720
Epoch 59/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7167 - loss: 0.5507 - val_accuracy: 0.6000 - val_loss: 0.7771
Epoch 60/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7223 - loss: 0.4977 - val_accuracy: 0.5867 - val_loss: 0.6941
Epoch 61/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7602 - loss: 0.5218 - val_accuracy: 0.5733 - val_loss: 0.7158
Epoch 62/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7397 - loss: 0.5463 - val_accuracy: 0.6000 - val_loss: 0.8184
Epoch 63/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7354 - loss: 0.5695 - val_accuracy: 0.6400 - val_loss: 0.7374
Epoch 64/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8168 - loss: 0.4862 - val_accuracy: 0.6267 - val_loss: 0.6504
Epoch 65/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8140 - loss: 0.4744 - val_accuracy: 0.6667 - val_loss: 0.6617
Epoch 66/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8271 - loss: 0.4083 - val_accuracy: 0.6400 - val_loss: 0.6267
Epoch 67/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8354 - loss: 0.4180 - val_accuracy: 0.6800 - val_loss: 0.8043
Epoch 68/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8033 - loss: 0.4330 - val_accuracy: 0.6933 - val_loss: 0.6075
Epoch 69/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8291 - loss: 0.3864 - val_accuracy: 0.5867 - val_loss: 1.4529
Epoch 70/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8277 - loss: 0.4811 - val_accuracy: 0.6933 - val_loss: 0.6310
Epoch 71/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8684 - loss: 0.3841 - val_accuracy: 0.7467 - val_loss: 0.6073
Epoch 72/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8777 - loss: 0.3665 - val_accuracy: 0.7067 - val_loss: 0.6608
Epoch 73/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8262 - loss: 0.4877 - val_accuracy: 0.7067 - val_loss: 1.3394
Epoch 74/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8187 - loss: 0.5660 - val_accuracy: 0.6667 - val_loss: 2.2006
Epoch 75/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8505 - loss: 0.8190 - val_accuracy: 0.7333 - val_loss: 0.9645
Epoch 76/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8506 - loss: 0.5496 - val_accuracy: 0.6800 - val_loss: 1.7859
Epoch 77/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8366 - loss: 0.4993 - val_accuracy: 0.7067 - val_loss: 0.5772
Epoch 78/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8448 - loss: 0.3604 - val_accuracy: 0.7333 - val_loss: 0.9576
Epoch 79/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8246 - loss: 0.4155 - val_accuracy: 0.7067 - val_loss: 1.7366
Epoch 80/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8448 - loss: 0.4808 - val_accuracy: 0.7200 - val_loss: 0.5662
Epoch 81/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7945 - loss: 1.3636 - val_accuracy: 0.4133 - val_loss: 9.3529
Epoch 82/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2843 - loss: 11.4103 - val_accuracy: 0.4133 - val_loss: 9.3529
Epoch 83/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2898 - loss: 11.3218 - val_accuracy: 0.4133 - val_loss: 9.3529
Epoch 84/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3275 - loss: 10.7206 - val_accuracy: 0.4133 - val_loss: 9.3529
Epoch 85/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2930 - loss: 11.2709 - val_accuracy: 0.4133 - val_loss: 9.3529
Epoch 86/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2882 - loss: 11.3482 - val_accuracy: 0.4133 - val_loss: 9.3529
Epoch 87/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3046 - loss: 11.0863 - val_accuracy: 0.4133 - val_loss: 9.3529
Epoch 88/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2521 - loss: 11.9235 - val_accuracy: 0.4133 - val_loss: 9.3529
Epoch 89/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2926 - loss: 11.2782 - val_accuracy: 0.4133 - val_loss: 9.3529
Epoch 90/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3052 - loss: 11.0774 - val_accuracy: 0.4133 - val_loss: 9.3529
Epoch 91/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2898 - loss: 11.3230 - val_accuracy: 0.4133 - val_loss: 9.3529
Epoch 92/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3275 - loss: 10.7205 - val_accuracy: 0.4133 - val_loss: 9.3529
Epoch 93/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2926 - loss: 11.2783 - val_accuracy: 0.4133 - val_loss: 9.3529
Epoch 94/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2438 - loss: 12.0561 - val_accuracy: 0.4133 - val_loss: 9.3529
Epoch 95/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2694 - loss: 11.6481 - val_accuracy: 0.4133 - val_loss: 9.3529
Epoch 96/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3197 - loss: 10.8460 - val_accuracy: 0.4133 - val_loss: 9.3529
Epoch 97/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2858 - loss: 11.3858 - val_accuracy: 0.4133 - val_loss: 9.3529
Epoch 98/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2613 - loss: 11.7770 - val_accuracy: 0.4133 - val_loss: 9.3529
Epoch 99/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2636 - loss: 11.7404 - val_accuracy: 0.4133 - val_loss: 9.3529
Epoch 100/100
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2762 - loss: 11.5389 - val_accuracy: 0.4133 - val_loss: 9.3529

In [12]:
highest_train_acc = max(history.history['accuracy'])
highest_train_acc

0.8616071343421936